/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeteranoRouteImport } from './routes/veterano'
import { Route as AsistenteRouteImport } from './routes/asistente'
import { Route as IndexRouteImport } from './routes/index'

const VeteranoRoute = VeteranoRouteImport.update({
  id: '/veterano',
  path: '/veterano',
  getParentRoute: () => rootRouteImport,
} as any)
const AsistenteRoute = AsistenteRouteImport.update({
  id: '/asistente',
  path: '/asistente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/veterano': typeof VeteranoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/veterano': typeof VeteranoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/asistente': typeof AsistenteRoute
  '/veterano': typeof VeteranoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/asistente' | '/veterano'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/asistente' | '/veterano'
  id: '__root__' | '/' | '/asistente' | '/veterano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AsistenteRoute: typeof AsistenteRoute
  VeteranoRoute: typeof VeteranoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veterano': {
      id: '/veterano'
      path: '/veterano'
      fullPath: '/veterano'
      preLoaderRoute: typeof VeteranoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asistente': {
      id: '/asistente'
      path: '/asistente'
      fullPath: '/asistente'
      preLoaderRoute: typeof AsistenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AsistenteRoute: AsistenteRoute,
  VeteranoRoute: VeteranoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
